openapi: 3.0.0
info:
  title: 'Crypto REST API'
  description: 'An API for blockchain applications'
  version: '0.0.1'

servers:
  - url: '/api'

paths:
  /latestBlock:
    get:
      operationId: 'block.get_latest'
      tags:
        - 'Latest Block'
      summary: 'Gets the latest block number'
      responses:
        '200':
          description: 'Success getting latest block number!'
